In [1]:
import json
import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import warnings
warnings.filterwarnings("ignore")

C:\Users\dehem\anaconda3\envs\projectdata\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset_json = [] 
import json

try:
    with open('data.json', 'r') as file:
        dataset_json = json.load(file)
    print("JSON data from file:")
except FileNotFoundError:
    print("Error: The file 'data.json' was not found.")
except json.JSONDecodeError:
    print("Error: Failed to decode JSON from the file (malformed JSON).")

JSON data from file:

In [3]:
# from datasets import Dataset
# import pandas as pd
# from sklearn.preprocessing import LabelEncoder

# # Load CSV
# df = pd.read_csv("data_01_labeled.csv")

# texts = []
# labels = []

# for _, row in df.iterrows():
#     if pd.notna(row["Experience"]):
#         texts.append(row["Experience"])
#         labels.append("Experience")

#     if pd.notna(row["Skill"]):
#         texts.append(row["Skill"])
#         labels.append("Skill")

#     if pd.notna(row["Qualification"]):
#         texts.append(row["Qualification"])
#         labels.append("Qualification")


# # ---------------------------
# # Apply Label Encoder
# # ---------------------------
# le = LabelEncoder()
# labels_encoded = le.fit_transform(labels)

# print("Label Mapping:")
# for label, index in zip(le.classes_, range(len(le.classes_))):
#     print(f"{label} → {index}")

# # Create HuggingFace Dataset
# dataset = Dataset.from_dict({
#     "text": texts,
#     "label": labels_encoded
# })

In [5]:
#Convert to Dataset
texts = [item["text"] for item in dataset_json]
labels = [item["label"] for item in dataset_json]

#Encode labels to integers
le = LabelEncoder()
labels_encoded = le.fit_transform(labels)

In [6]:
# Train/test split

from sklearn.model_selection import train_test_split

# Step 1: 70% train, 30% temp
train_texts, temp_texts, train_labels, temp_labels = train_test_split(
    texts,
    labels_encoded,
    test_size=0.30,
    stratify=labels_encoded,
    random_state=42
)

# Step 2: Split temp into 15% val and 15% test
val_texts, test_texts, val_labels, test_labels = train_test_split(
    temp_texts,
    temp_labels,
    test_size=0.50,
    stratify=temp_labels,
    random_state=42
)

print("Train size:", len(train_texts))
print("Validation size:", len(val_texts))
print("Test size:", len(test_texts))


train_dataset = Dataset.from_dict({"text": train_texts, "label": train_labels})
val_dataset = Dataset.from_dict({"text": val_texts, "label": val_labels})

Train size: 1103
Validation size: 236
Test size: 237

In [7]:
# ========================
# Step 2: Tokenization
# ========================
model_name = "prajjwal1/bert-tiny"  # lightweight and fast
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch["text"], padding='max_length', truncation=True, max_length=128)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)

# Set format for PyTorch
train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

Map: 100%|████████████████████████████████████████████████████████████████| 1103/1103 [00:00<00:00, 5754.03 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 236/236 [00:00<00:00, 5356.19 examples/s]

In [8]:


from transformers import AutoModelForSequenceClassification

num_labels = len(le.classes_)

# This will print progress while downloading/loading
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    force_download=False,  # Set True if you want to re-download
    local_files_only=False  # Allow download if not cached
)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [9]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(pred):
    logits, labels = pred
    predictions = logits.argmax(axis=-1)

    precision, recall, f1_weighted, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted"
    )

    _, _, f1_macro, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="macro"
    )

    acc = accuracy_score(labels, predictions)

    return {
        "accuracy": acc,
        "f1": f1_weighted,
        "f1_macro": f1_macro,
        "precision": precision,
        "recall": recall
    }

In [10]:
training_args = TrainingArguments(
    output_dir="./cv_classifier_model-v1",
    num_train_epochs=5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir="./logs",
    learning_rate=2e-5,
    eval_strategy='epoch', 
    save_strategy='epoch',
    metric_for_best_model="eval_f1", 
    greater_is_better=True, 
    weight_decay=0.01, 
    logging_steps=50,
    save_safetensors=False,
    load_best_model_at_end=True  # no need for best model
)

In [11]:
# ========================
# Step 6: Trainer
# ========================
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
)

In [12]:
# ========================
# Step 7: Train
# ========================
trainer.train()

TrainOutput(global_step=690, training_loss=0.7462636007778887, metrics={'train_runtime': 89.8037, 'train_samples_per_second': 61.412, 'train_steps_per_second': 7.683, 'total_flos': 1752230388480.0, 'train_loss': 0.7462636007778887, 'epoch': 5.0})

In [14]:
# ========================
# Step 9: Example Inference
# ========================
def predict(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
    outputs = model(**inputs)
    preds = torch.argmax(outputs.logits, dim=1).item()
    label = le.inverse_transform([preds])[0]
    return label

# Example prediction
example_text = "With 4 years of experience also I specialize in using Python and R for statistical analysis, machine learning, and data visualization."
print("Predicted Label:", predict(example_text))

Predicted Label: SKILL

In [15]:
import pandas as pd

In [16]:
df_csv_test = pd.read_csv('data 02.csv')

In [17]:
df_csv_test = df_csv_test [253:]

In [18]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\dehem\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [19]:
unlabeled_texts = []
for i in df_csv_test['Resume']:
    sentences = sent_tokenize(i)
    unlabeled_texts.extend(sentences)

In [20]:
# Step 2: Tokenize unlabeled data
unlabeled_dataset = Dataset.from_dict({"text": unlabeled_texts})
unlabeled_dataset = unlabeled_dataset.map(tokenize, batched=True)
unlabeled_dataset.set_format(type="torch", columns=["input_ids", "attention_mask"])

Map: 100%|██████████████████████████████████████████████████████████████████| 882/882 [00:00<00:00, 5814.45 examples/s]

In [21]:
# Step 3: Get pseudo-labels from your trained model
model.eval()
pseudo_labels = []
for batch in unlabeled_dataset:
    input_ids = batch["input_ids"].unsqueeze(0)  # batch of 1
    attention_mask = batch["attention_mask"].unsqueeze(0)
    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        pred = torch.argmax(outputs.logits, dim=1).item()
    pseudo_labels.append(pred)

In [22]:
# Step 4: Create pseudo-labeled dataset
pseudo_dataset = Dataset.from_dict({
    "text": unlabeled_texts,
    "label": pseudo_labels
})

In [23]:
train_dataset = train_dataset.map(tokenize, batched=True)
pseudo_dataset = pseudo_dataset.map(tokenize, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
pseudo_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

Map: 100%|████████████████████████████████████████████████████████████████| 1103/1103 [00:00<00:00, 5328.27 examples/s]
Map: 100%|██████████████████████████████████████████████████████████████████| 882/882 [00:00<00:00, 6944.56 examples/s]

In [24]:
from datasets import concatenate_datasets
# Step 5: Combine with original labeled data
combined_dataset = concatenate_datasets([train_dataset, pseudo_dataset])

In [25]:
# Step 6: Retrain / fine-tune the model on combined dataset
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=combined_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)
trainer.train()

TrainOutput(global_step=1245, training_loss=0.257061536245078, metrics={'train_runtime': 186.8596, 'train_samples_per_second': 53.115, 'train_steps_per_second': 6.663, 'total_flos': 3153379257600.0, 'train_loss': 0.257061536245078, 'epoch': 5.0})

In [13]:
model.save_pretrained("./cv_classifier_model-v1")
tokenizer.save_pretrained("./cv_classifier_model-v1")

('./cv_classifier_model-v1\\tokenizer_config.json',
 './cv_classifier_model-v1\\special_tokens_map.json',
 './cv_classifier_model-v1\\vocab.txt',
 './cv_classifier_model-v1\\added_tokens.json',
 './cv_classifier_model-v1\\tokenizer.json')

In [25]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained("./cv_classifier_model-v1")
tokenizer = AutoTokenizer.from_pretrained("./cv_classifier_model-v1")

## Upload CV and Classify the data

In [52]:

def classify_line(line):
    inputs = tokenizer(line, return_tensors="pt", truncation=True)
    outputs = model(**inputs)
    return outputs.logits.argmax(dim=1).item()

In [53]:
import pdfplumber
import re
text = ""
with pdfplumber.open("Pawan Perera.pdf") as pdf:
    for page in pdf.pages:
        text += page.extract_text() + "\n"

In [54]:
github_links = re.findall(r"github.com/[A-Za-z0-9_-]+", text)
github_link = "https://"+github_links[0]
print(github_link)

https://github.com/PinsaraPerera

In [55]:
# import re

# clean_text = re.sub(r"[^a-zA-Z0-9\s]", "", text.lower())

In [56]:
lines = [l.strip() for l in text.split("\n") if len(l.strip()) > 3]

In [57]:
LABELS = {
    0: "SKILL",
    1: "QUALIFICATION",
    2: "EXPERIENCE"
}

In [58]:
result = {
    "skills": [],
    "qualifications": [],
    "experience": []
}

for line in lines:
    label = LABELS[classify_line(line)]
    if label == "SKILL":
        result["skills"].append(line)
    elif label == "QUALIFICATION":
        result["qualifications"].append(line)
    elif label == "EXPERIENCE":
        result["experience"].append(line)

## Job posting classifications

In [40]:
with open('Dataset_jotpars.csv', 'rb') as f:
    content = f.read()

# Decode safely, ignoring bad bytes
text = content.decode('utf-8', errors='ignore')

# Save a clean CSV
with open('Dataset_jotpars_clean.csv', 'w', encoding='utf-8') as f:
    f.write(text)

# Read the clean CSV
df_job = pd.read_csv('Dataset_jotpars_clean.csv')

In [41]:
df_job['full job post'] = df_job['requirment'] + ' ' + df_job['description']

In [42]:
df_job['full job post']

0       r2  ,  soa  ,  t-sql  ,  database  ,  security...
1       software development  ,  satellite  ,  android...
2       hibernate  ,  java developer  ,  spring  ,  sp...
3       css  ,  team player  ,  ajax  ,  javascript  ,...
4       css  ,  html5  ,  ajax  ,  oop  ,  windows pla...
                              ...
8792    css  ,  wordpress  ,  php  ,  html  ,  mysql  ...
8793    css  ,  wordpress  ,  wordpress cms  ,  bootst...
8794    wordpress  ,  html5  ,  symfony  ,  jquery  , ...
8795    css  ,  wordpress  ,  mobile  ,  php  ,  web d...
8796    css  ,  wordpress  ,  php  ,  html  ,  mysql  ...
Name: full job post, Length: 8797, dtype: object

In [43]:
job_lines = []

for rec in df_job['full job post'][4237:4238]:  # slice first 500
    lines_1 = [line.strip() for line in rec.split(",") or rec.split('\n')  if len(line.strip()) > 3]
    job_lines.extend(lines_1)  # add all lines to job_lines

In [44]:
result_jd = {
    "skills": [],
    "qualifications": [],
    "experience": [],
    "other":[]
}

for line in job_lines:
    label = LABELS[classify_line(line)]
    if label == "SKILL":
        result_jd["skills"].append(line)
    elif label == "QUALIFICATION":
        result_jd["qualifications"].append(line)
    elif label == "EXPERIENCE":
        result_jd["experience"].append(line)
    else:
         result_jd['other'].append(line)

# Similarity Score is generated in here

In [38]:


from sentence_transformers import SentenceTransformer, util

# Load a pre-trained embedding model
model2 = SentenceTransformer('all-MiniLM-L6-v2')

# Encode texts
cv_embedding_skill = model2.encode(result['skills'], convert_to_tensor=True)
job_embedding_skill = model2.encode(result_jd['skills'], convert_to_tensor=True)

'(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: e8b3dc1a-df4b-4d22-be85-780488b15125)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/./modules.json
Retrying in 1s [Retry 1/5].

In [39]:
similarity_score_skill = util.cos_sim(cv_embedding_skill, job_embedding_skill).max().item()
print(f"Semantic Similarity Score skills : {similarity_score_skill*100:.2f}%")

Semantic Similarity Score skills : 50.85%

In [40]:
# quqlification meching for the cv 
cv_embedding_qualification = model2.encode(result['qualifications'], convert_to_tensor=True)
job_embedding_qualification = model2.encode(result_jd['qualifications'], convert_to_tensor=True)

similarity_score_qualification = util.cos_sim(cv_embedding_qualification,job_embedding_qualification).max().item()
print(f"Qualification Similarity Score : {similarity_score_qualification*100:.2f}%")

Qualification Similarity Score : 63.97%

In [41]:
# experience meching for the cv 
cv_embedding_experience = model2.encode(result['experience'], convert_to_tensor=True)
job_embedding_experience = model2.encode(result_jd['experience'], convert_to_tensor=True)

similarity_score_experience = util.cos_sim(cv_embedding_experience,job_embedding_experience).max().item()
print(f"Experience Similarity Score : {similarity_score_experience*100:.2f}%")

Experience Similarity Score : 61.56%

In [42]:
WEIGHTS = {
    "skills": 0.4,
    "experience": 0.4,
    "qualification": 0.2
}
# in here we give this as assumption means

In [43]:


final_score = (
    WEIGHTS["skills"] * similarity_score_skill +
    WEIGHTS["experience"] * similarity_score_experience +
    WEIGHTS["qualification"] * similarity_score_qualification
)

print(f"Final CV–JD Match Score: {final_score * 100:.2f}%")

Final CV–JD Match Score: 57.76%